export const LIST_ITEM_REQUEST = "LIST_ITEM_REQUEST";
export const LIST_ITEM_SUCCESS = "LIST_ITEM_SUCCESS";
export const LIST_ITEM_FAILURE = "LIST_ITEM_FAILURE";

export const INSERT_ITEM_REQUEST = "INSERT_ITEM_REQUEST";
export const INSERT_ITEM_SUCCESS = "INSERT_ITEM_SUCCESS";
export const INSERT_ITEM_FAILURE = "INSERT_ITEM_FAILURE";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";
